import {build} from 'esbuild';
import {mkdir,readFile,writeFile,copyFile,readdir} from 'node:fs/promises';
await mkdir('dist',{recursive:true});
const worker=await build({entryPoints:['src/worker.js'],bundle:true,write:false,format:'iife',target:'es2022',minify:true});
await build({entryPoints:['src/app.js'],outfile:'dist/app.js',bundle:true,format:'iife',target:'es2022',minify:true,plugins:[{name:'inline-worker',setup(b){b.onResolve({filter:/\.\/worker\.js$/},()=>({path:'worker-source',namespace:'inline'}));b.onLoad({filter:/.*/,namespace:'inline'},()=>({contents:worker.outputFiles[0].text,loader:'text'}));}}]});
await copyFile('src/style.css','dist/style.css');await copyFile('index.html','dist/index.html');
await copyFile('vendor/koalasand/LICENSE','dist/KoalaSand-LICENSE.txt');
await writeFile('dist/wallpaper.html',await readFile('index.html','utf8'));
for(const name of await readdir('public'))await copyFile('public/'+name,'dist/'+name);
console.log('BUILD_PASS: dist/ — web, Electron and Lively share one build.');
